name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Replace Firebase secrets in config and copy to build
        shell: bash
        run: |
          cp scripts/firebase-config.template.js scripts/firebase-config.js

          escape() {
            printf '%s' "$1" | sed 's/[\/&]/\\&/g'
          }

          sed -i "s|__FIREBASE_API_KEY__|$(escape "${{ secrets.FIREBASE_API_KEY }}")|g" scripts/firebase-config.js
          sed -i "s|__FIREBASE_AUTH_DOMAIN__|$(escape "${{ secrets.FIREBASE_AUTH_DOMAIN }}")|g" scripts/firebase-config.js
          sed -i "s|__FIREBASE_PROJECT_ID__|$(escape "${{ secrets.FIREBASE_PROJECT_ID }}")|g" scripts/firebase-config.js
          sed -i "s|__FIREBASE_STORAGE_BUCKET__|$(escape "${{ secrets.FIREBASE_STORAGE_BUCKET }}")|g" scripts/firebase-config.js
          sed -i "s|__FIREBASE_MESSAGING_SENDER_ID__|$(escape "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}")|g" scripts/firebase-config.js
          sed -i "s|__FIREBASE_APP_ID__|$(escape "${{ secrets.FIREBASE_APP_ID }}")|g" scripts/firebase-config.js

          mkdir -p build/scripts
          mv scripts/firebase-config.js build/scripts/firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
